// Result screen, depot recruits and visible automatic coaching.
let scriptChangeText=campaign.coachLog||'No script changes yet.',coachActivity='';
$('menuButton').parentNode?.after?.($('coachMainPanel'));$('coachDialog').append($('coachBriefFallback'));
function rankBadge(tier){const badge=document.createElement('span');badge.className='rank-stars';badge.setAttribute('aria-label',tier+' stars');for(let i=0;i<tier;i++){const star=document.createElement('span');star.className='rank-star';badge.append(star)}return badge}
const rankedRoster=renderRoster;renderRoster=function(){rankedRoster();for(const [i,card]of [...$('rosterGrid').children].entries()){const detail=card.children[1];if(detail&&roster[i]){detail.textContent=detail.textContent.replace(/★+ · /,'');detail.append(rankBadge(roster[i].tier))}}};
const compactDepot=renderBase;renderBase=function(){compactDepot();for(const [i,card]of [...$('depotUnits').children].entries()){const detail=card.children[1];detail.textContent=unitTypes[roster[i].type].name+' · '+capacityFor(roster[i])+' orders';detail.append(rankBadge(roster[i].tier));if(card.children[3])card.children[3].hidden=card.children[3].disabled}const pending=mode==='won'&&!!levelReward&&!levelReward.unit;$('depotRecruitSection').hidden=!pending;const choices=$('depotRecruitChoices');choices.replaceChildren();if(pending)for(const type of levelReward.offerTypes){const b=rewardButton(unitTypes[type].name,roster.length<economy.slots?'Add to squad':'Keep in reserve',()=>chooseReward({unitType:type,action:'add'}));b.className='depot-recruit';b.append(rankBadge(1));choices.append(b)}if(pending){$('depotNextNote').textContent='Choose your recruit, then a free upgrade.';$('depotRewardNote').textContent='Choose your recruit above to unlock the free upgrade.'}syncCoachUI()};
function setScriptNote(text){scriptChangeText=text;campaign.coachLog=text;saveRoster();syncCoachUI()}
function syncCoachUI(){if(!$('coachMainStatus'))return;$('coachMainStatus').textContent=coachRequest?'Analyzing battle · Full guide included':coachSettings.enabled?(coachSettings.provider==='ollama'?'Local coach · ':'Coach · ')+coachSettings.model:'Coach off · No automatic requests';$('scriptChangeNote').textContent=scriptChangeText;$('depotScriptNote').textContent=scriptChangeText;$('analyzeMain').textContent=coachRequest?'Analyzing…':coachSettings.enabled?'Analyze again':'Set up coach';$('analyzeMain').disabled=!!coachRequest||mode==='running';$('runCoach').disabled=!!coachRequest||mode==='running';$('applyMainDraft').hidden=!coachDraft;$('applyMainDraft').disabled=mode==='running';$('deploy').disabled=mode==='running'||mode==='won'||!!coachRequest;$('coachStatus').textContent=coachActivity||(!coachSettings.enabled?'Enable a model to analyze battles automatically.':'Full Python documentation is included in each request.')}
$('analyzeMain').onclick=()=>coachSettings.enabled?requestCoach():openCoachSettings();$('configureMain').onclick=openCoachSettings;$('applyMainDraft').onclick=()=>applyCoachScripts();
function lineChanges(before,after){const a=before.replace(/\r/g,'').split('\n'),b=after.replace(/\r/g,'').split('\n');if(before===after)return{added:0,removed:0};const prev=new Array(b.length+1).fill(0);for(const x of a){let diagonal=0;for(let j=1;j<=b.length;j++){const old=prev[j];prev[j]=x===b[j-1]?diagonal+1:Math.max(prev[j],prev[j-1]);diagonal=old}}const shared=prev[b.length];return{added:b.length-shared,removed:a.length-shared}}
function coachChangeCounts(draft){let added=0,removed=0,units=0;for(const row of draft.scripts){const current=roster.find(u=>u.id===row.id)?.unitScript||'',diff=lineChanges(current,row.script);added+=diff.added;removed+=diff.removed;if(diff.added||diff.removed)units++}if(draft.squadScript!==undefined){const diff=lineChanges(campaign.orders||'',draft.squadScript);added+=diff.added;removed+=diff.removed;if(diff.added||diff.removed)units++}return{added,removed,units}}
coachSnapshot=function(ids=null){return JSON.stringify({units:roster.filter(u=>!ids||ids.includes(u.id)).map(u=>({id:u.id,script:u.unitScript})),squad:campaign.orders})};
requestCoach=async function(){if(!coachSettings.enabled){coachActivity='Opt in to enable automatic battle analysis.';syncCoachUI();return}if(!lastBattleReport||coachRequest||mode==='running'){coachActivity=mode==='running'?'Analysis is available after the battle.':'Play a campaign battle first.';syncCoachUI();return}const controller=new AbortController(),generation=++coachGeneration,ids=roster.map(u=>u.id),snapshot=coachSnapshot(ids),report=lastBattleReport;coachAttemptedReport=report;coachRequest=controller;coachDraft=null;$('applyCoachDraft').hidden=true;$('coachDraftReview').hidden=true;coachActivity='Analyzing Round '+report.round+' · Sending full function documentation.';$('coachMessage').textContent=coachActivity;setScriptNote('Round '+report.round+' · Analyzing… scripts unchanged until validated.');renderBase();try{const response=await fetch('/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...coachSettings,key:coachApiKey,report,units:roster.map(u=>({id:u.id,type:u.type,tier:u.tier,script:u.unitScript})),squadScript:campaign.orders}),signal:controller.signal}),data=await response.json();if(!response.ok||data.error)throw Error(data.error||'Coach unavailable.');if(generation!==coachGeneration||!coachSettings.enabled)return;if(snapshot!==coachSnapshot(ids))throw Error('Units or scripts changed during analysis. Analyze again.');coachDraft=validateCoachDraft(data);coachDraft.snapshot=snapshot;coachDraft.snapshotIds=ids;coachDraft.round=report.round;const diff=coachChangeCounts(coachDraft);coachActivity='Full guide sent ('+(data.documentation?.characters||'all')+' characters). '+(data.summary||'Analysis complete.');if(!diff.units){coachDraft=null;setScriptNote('Round '+report.round+' · No script changes.');$('applyCoachDraft').hidden=true;$('coachDraftReview').hidden=true}else{$('coachDraftReview').hidden=false;$('applyCoachDraft').hidden=false;$('coachDraftText').textContent=data.scripts.map(row=>(roster.find(u=>u.id===row.id)?.name||row.id)+'\n'+row.script).join('\n\n')+(data.squadScript!==undefined?'\n\nSquad script\n'+data.squadScript:'');setScriptNote('Round '+report.round+' · Draft: '+diff.added+' lines added / '+diff.removed+' removed · Not applied.');if(coachSettings.autoApply)applyCoachScripts()}$('coachMessage').textContent=coachActivity}catch(e){if(generation===coachGeneration){coachDraft=null;coachActivity=e.name==='AbortError'?'Analysis cancelled.':e.message;setScriptNote('Round '+report.round+' · No script changes · '+coachActivity);$('coachMessage').textContent=coachActivity}}finally{if(coachRequest===controller)coachRequest=null;renderBase();syncCoachUI()}};
applyCoachScripts=function(){if(!coachDraft||mode==='running'||coachSnapshot(coachDraft.snapshotIds)!==coachDraft.snapshot){coachActivity='Draft is stale or a battle is running. Analyze again.';syncCoachUI();return}const draft=validateCoachDraft(coachDraft),diff=coachChangeCounts(draft),fromRound=draft.round||lastBattleReport?.round||round;for(const row of draft.scripts)roster.find(u=>u.id===row.id).unitScript=row.script;if(draft.squadScript!==undefined){campaign.orders=draft.squadScript;squadScript=draft.squadScript;$('prompt').value=squadScript}saveProgram();preview();coachDraft=null;$('applyCoachDraft').hidden=true;$('coachDraftReview').hidden=true;coachActivity='Validated scripts saved for the next battle.';setScriptNote(diff.units?'Round '+fromRound+' · '+diff.added+' lines added / '+diff.removed+' removed · '+diff.units+' scripts updated.':'Round '+fromRound+' · No script changes.')};
$('applyCoachDraft').onclick=applyCoachScripts;$('runCoach').onclick=()=>requestCoach();
const saveCoachPreferences=$('saveCoach').onclick;$('saveCoach').onclick=()=>{saveCoachPreferences();syncCoachUI();if(coachSettings.enabled&&lastBattleReport&&coachAttemptedReport!==lastBattleReport)requestCoach()};
$('coachProvider').onchange=()=>{const presets={ollama:['http://127.0.0.1:11434/api/chat','qwen2.5-coder:7b'],gemini:['https://generativelanguage.googleapis.com/v1beta',''],openai:['https://api.openai.com/v1/responses',''],compatible:['','']};const [endpoint,model]=presets[$('coachProvider').value];$('coachEndpoint').value=endpoint;$('coachModel').value=model;$('coachModel').placeholder='Model ID from your provider account';$('coachKey').value=''};
$('copyBattleBrief').onclick=async()=>{try{const response=await fetch('/api/coach/reference'),data=await response.json();if(!response.ok||!data.text)throw Error('Start the local server to copy the guide.');const brief='Build Tank Tactics restricted Python tick(unit, squad) scripts using this guide. Suggest changes supported by the report. Return each unit script separately, labelled with its unit ID.\n\n'+data.text+'\n\nBattle and current scripts:\n'+JSON.stringify({report:lastBattleReport,units:roster.map(u=>({id:u.id,type:u.type,tier:u.tier,script:u.unitScript})),squadScript:campaign.orders},null,2);$('coachBriefFallback').value=brief;await navigator.clipboard.writeText(brief);$('coachMessage').textContent='Battle and full guide copied. Paste into ChatGPT, AI Studio or your preferred chatbot.'}catch(e){$('coachMessage').textContent=e.message;if($('coachBriefFallback').value){$('coachBriefFallback').hidden=false;$('coachBriefFallback').select?.();$('coachMessage').textContent='Copy the battle brief from the text box below.'}}};
function renderBattleResult(win){$('rewardTitle').textContent=win?'Victory':'Defeat';const intro=$('rewardDialog').querySelector?.('p');if(intro)intro.textContent=win?'Prepare your squad and choose a recruit at Field Base.':'Regroup, adjust your scripts and prepare at Field Base.';const eyebrow=$('rewardDialog').querySelector?.('.eyebrow');if(eyebrow)eyebrow.textContent='BATTLE COMPLETE';const root=$('rewards');root.replaceChildren();const report=lastBattleReport,points=campaign.lastPoints||{total:0,outcome:0,eliminations:0,survival:0};for(const text of ['Round '+(report?.round||round)+' · '+Math.round(report?.durationSeconds||elapsed)+' seconds','+'+points.total+' points · Practice run score '+(campaign.practiceScore||0),'Outcome '+points.outcome+' · Eliminations '+points.eliminations+' · Survivors '+points.survival,win?'Your recruit and free upgrade are waiting at Field Base.':campaign.lives>0?campaign.lives+' lives remaining.':'Run ended. Start a new run from Field Base.']){const p=document.createElement('p');p.textContent=text;root.append(p)}$('claimLevel').disabled=false;$('claimLevel').textContent='Continue to Field Base'}
renderLevelRewards=function(){renderBattleResult(true)};$('claimLevel').onclick=()=>{if(mode==='won'||mode==='lost')openFieldBase()};
const resultFinish=finish;finish=function(win){if(mode!=='running')return;const practice=!replaying&&!onlinePlaying;resultFinish(win);if(!practice)return;campaign.lastPoints=battlePoints(win,battleUnits);campaign.practiceScore=(campaign.practiceScore||0)+campaign.lastPoints.total;saveRoster();if(autoRestartTimer){clearTimeout(autoRestartTimer);autoRestartTimer=null}closeFieldBase();renderBattleResult(win);$('rewardDialog').showModal();if(coachSettings.enabled&&coachAttemptedReport!==lastBattleReport)requestCoach();else if(!coachSettings.enabled)setScriptNote('Round '+round+' · No script changes (coach off).');if(!win&&autoRestart&&!coachSettings.enabled&&campaign.lives>0)autoRestartTimer=setTimeout(()=>{$('rewardDialog').close();closeFieldBase();deploy()},3000);syncCoachUI()};
const clearScoreRun=resetRun;resetRun=function(){clearScoreRun();campaign.practiceScore=0;campaign.lastPoints=null;coachActivity='';coachAttemptedReport=null;setScriptNote('New run · No script changes yet.')};$('reset').onclick=()=>resetRun();
const actionDeploy=deploy;deploy=function(){if(coachRequest){coachActivity='Wait for battle analysis before deploying.';syncCoachUI();return}const result=actionDeploy();syncCoachUI();return result};$('deploy').onclick=deploy;
const resultOpenBase=openFieldBase;openFieldBase=function(){resultOpenBase();if(inFieldBase)$('fieldBaseScreen').scrollIntoView?.({block:'start',behavior:'instant'})};$('baseButton').onclick=openFieldBase;
syncCoachUI();
const scoreHud=updateHud;updateHud=function(){scoreHud();$('winsLabel').textContent='Run wins: '+wins+' · Practice score '+(campaign.practiceScore||0)};
const deployFromDepot=$('depotDeploy').onclick;$('depotDeploy').onclick=()=>{if(mode==='lost'&&campaign.lives<=0){resetRun();openFieldBase();return}deployFromDepot()};
const endRunDepot=renderBase;renderBase=function(){endRunDepot();if(mode==='lost'&&campaign.lives<=0){$('depotDeploy').textContent='Start new run';$('depotDeploy').disabled=!!coachRequest;$('depotNextNote').textContent='Run complete · Prepare a fresh squad.'}};
let onlineResultShown=false;
function showOnlineBattleResult(win,data){onlineResultShown=true;$('rewardTitle').textContent=win?'Multiplayer victory':'Multiplayer defeat';const intro=$('rewardDialog').querySelector?.('p');if(intro)intro.textContent='Server-confirmed battle result.';const root=$('rewards');root.replaceChildren();for(const text of ['+'+data.points+' leaderboard points','Online credits: '+(win?60:15)+'. Refresh your online armory to see your balance.']){const p=document.createElement('p');p.textContent=text;root.append(p)}$('claimLevel').disabled=false;$('claimLevel').textContent='Return to battlefield';$('rewardDialog').showModal();syncCoachUI()}
const campaignResultContinue=$('claimLevel').onclick;$('claimLevel').onclick=()=>{if(onlineResultShown){onlineResultShown=false;$('rewardDialog').close();return}campaignResultContinue()};
