// Between-battle progression. Campaign purchases remain separate from online accounts.
let inFieldBase=false,lastBattleReport=null,coachDraft=null,coachRequest=null,coachGeneration=0,coachAttemptedReport=null;
if(!campaign.depotVersion){for(const b of campaign.base||[])economy.credits+=(baseTypes[b.kind]?.price||0)+70*(b.tier-1)*b.tier/2;campaign.base=[];campaign.depotVersion=1;saveRoster()}
function depotUpgradePrice(u,kind){return 80+20*(u.upgrades?.[kind]||0)}
function depotCombine(unit){if(mode==='running'||compiling)return;const target=levelReward?.upgradeTarget===unit.id;depotEdit(()=>combineUnits(unit.type,unit.tier));if(target&&levelReward)levelReward.upgradeTarget=selectedId;renderBase()}
function depotChooseUnit(id){if(!roster.some(u=>u.id===id))return;selectedId=id;saveRoster();if(mode!=='won')resetPositions();preview();renderBase()}
function buyDepotUpgrade(kind){if(mode==='running'||compiling||!permanentKinds.includes(kind))return;const u=selectedUnit(),n=u.upgrades?.[kind]||0;const free=mode==='won'&&levelReward?.unit&&!levelReward.tactic&&levelReward.tacticOptions.some(o=>o.kind===kind);if(n>=20&&!free)return;if(free){levelReward.upgradeTarget=u.id;chooseReward(levelReward.tacticOptions.find(o=>o.kind===kind));depotCompleteRewards()}else{const cost=depotUpgradePrice(u,kind);if(economy.credits<cost)return;economy.credits-=cost;u.upgrades=u.upgrades||{};u.upgrades[kind]=n+1;saveRoster();if(mode!=='won')resetPositions();preview()}renderBase();$('depotMessage').textContent=permanentNames[permanentKinds.indexOf(kind)]+' applied to '+u.name+'.'}
renderBase=function(){const u=selectedUnit(),root=$('depotUnits');root.replaceChildren();$('depotBalance').textContent=economy.credits+' credits · Round '+round+' · '+roster.length+'/'+economy.slots+' squad slots';for(const unit of roster){const card=document.createElement('div');card.className='depot-unit'+(unit.id===selectedId?' active':'');const name=document.createElement('button');name.className='unit-name';name.textContent=unit.name;name.onclick=e=>showUnitTooltip(unit,e?.clientX||16,e?.clientY||120,true);const p=document.createElement('p');p.textContent=unitTypes[unit.type].name+' · '+'★'.repeat(unit.tier)+' · '+capacityFor(unit)+' order slots';const select=document.createElement('button');select.className='primary';select.textContent=unit.id===selectedId?'Selected':'Select to upgrade';select.disabled=mode==='running';select.onclick=()=>depotChooseUnit(unit.id);const combine=document.createElement('button');combine.textContent='Combine 3 · upgrade stars';combine.disabled=unit.tier>=3||roster.filter(x=>x.type===unit.type&&x.tier===unit.tier).length<3||mode==='running'||compiling;combine.onclick=()=>{depotChooseUnit(unit.id);depotCombine(unit)};card.append(name,p,select,combine);attachUnitTooltip(card,unit);root.append(card)}$('depotUpgradeTitle').textContent='Train '+u.name;const pending=mode==='won'&&levelReward?.unit&&!levelReward.tactic;$('depotRewardNote').textContent=pending?'Choose one highlighted victory upgrade free.':'All upgrades are permanent for this unit.';const grid=$('depotUpgrades');grid.replaceChildren();for(let i=0;i<permanentKinds.length;i++){const kind=permanentKinds[i],n=u.upgrades?.[kind]||0,free=pending&&levelReward.tacticOptions.some(o=>o.kind===kind),cost=depotUpgradePrice(u,kind),card=document.createElement('div');card.className='depot-upgrade'+(free?' free':'');const h=document.createElement('h3');h.textContent=permanentNames[i];const p=document.createElement('p');p.textContent=permanentEffects[i];const level=document.createElement('small');level.textContent='Training '+n+' / 20';const button=document.createElement('button');button.className=free?'primary':'tiny';button.textContent=n>=20?(free?'Claim 30 credits':'Fully trained'):free?'Claim free upgrade':'Train · '+cost+' credits';button.disabled=mode==='running'||compiling||(n>=20&&!free)||(!free&&economy.credits<cost);button.onclick=()=>buyDepotUpgrade(kind);card.append(h,p,level,button);grid.append(card)}$('depotDeploy').disabled=mode==='running'||compiling||!!(mode==='won'&&(!levelReward?.unit||!levelReward?.tactic))||mode==='lost'&&campaign.lives<=0||!!coachRequest;$('depotDeploy').textContent=mode==='won'?'Deploy Round '+(round+1):mode==='lost'?'Retry Round '+round:'Deploy Round '+round;$('depotNextNote').textContent=pending?'Claim your free upgrade before deploying.':mode==='lost'&&campaign.lives<=0?'Run ended. Start a new run in Menu.':coachRequest?'Waiting for coach analysis…':'Your squad is ready.'}
function openFieldBase(){if(mode==='running'||compiling)return;if(autoRestartTimer){clearTimeout(autoRestartTimer);autoRestartTimer=null}hideUnitTooltip();$('menuDialog').close();$('rewardDialog').close();$('fieldBaseScreen').hidden=false;$('battleShell').hidden=true;inFieldBase=true;renderBase();if(coachSettings.enabled&&lastBattleReport&&coachAttemptedReport!==lastBattleReport&&!replaying&&!onlinePlaying)requestCoach()}
function closeFieldBase(){hideUnitTooltip();$('fieldBaseScreen').hidden=true;$('battleShell').hidden=false;inFieldBase=false}
$('baseButton').onclick=openFieldBase;$('leaveDepot').onclick=()=>{if(mode==='won'&&levelReward){$('depotMessage').textContent='Claim the victory upgrade and deploy from Field Base.';return}closeFieldBase()};
const depotCompleteRewards=completeLevelRewards;$('depotDeploy').onclick=()=>{if($('depotDeploy').disabled)return;if(mode==='won')depotCompleteRewards();closeFieldBase();deploy()};
$('depotArmory').onclick=()=>{renderLoadout();$('loadoutDialog').showModal()};$('depotStore').onclick=()=>{renderStore();$('storeDialog').showModal()};$('depotScripts').onclick=()=>$('scriptsButton').onclick();$('depotCoach').onclick=()=>openCoachSettings();
renderLevelRewards=function(){if(!levelReward)return;const root=$('rewards');root.replaceChildren();$('rewardTitle').textContent='Victory · Choose your recruit';if(levelReward.unit){const p=document.createElement('p');p.textContent=levelReward.unit;root.append(p)}else for(const type of levelReward.offerTypes)root.append(rewardButton('Recruit '+unitTypes[type].name+' ★',roster.length<economy.slots?'Add to squad · combine three matching copies':'Squad full · waits in reserve',()=>chooseReward({unitType:type,action:'add'})));const p=document.createElement('p');p.textContent='Your permanent upgrade is waiting at Field Base.';root.append(p);$('claimLevel').disabled=!levelReward.unit;$('claimLevel').textContent='Return to Field Base'};
$('claimLevel').onclick=()=>{if(mode==='won'&&levelReward?.unit)openFieldBase()};
const depotReward=chooseReward;chooseReward=function(option){depotReward(option);if(inFieldBase)renderBase()};
const depotFinish=finish;finish=function(win){if(mode!=='running')return;if(!replaying&&!onlinePlaying){lastBattleReport=collectBattleReport(win);coachDraft=null;}$('applyCoachDraft').hidden=true;$('coachDraftReview').hidden=true;depotFinish(win);hideUnitTooltip();if(!win&&(!autoRestart||coachSettings.enabled)&&!replaying&&!onlinePlaying)openFieldBase();};
const depotReset=resetRun;resetRun=function(){coachGeneration++;if(coachRequest)coachRequest.abort();coachRequest=null;coachDraft=null;lastBattleReport=null;closeFieldBase();depotReset()};$('reset').onclick=()=>resetRun();
const baseStore=renderStore;renderStore=function(){baseStore();if(inFieldBase)renderBase()};
const baseEquipment=equipGear;equipGear=function(id,slot){baseEquipment(id,slot);if(inFieldBase)renderBase()};
function unitTooltipRows(u){const s=u.stats||unitStats(u),percent=v=>(100*(v||0)).toFixed(1)+'%',num=v=>Number(v||0).toFixed(1);return[['Health',Math.ceil(u.hp??s.hp)+' / '+Math.round(u.maxHp??s.hp)],['Damage',num(s.damage)],['Armor',percent(s.armor)],['Resistance',percent(s.damageResistance)],['Speed',num(s.speed)],['Magazine',(u.ammo??s.mag)+' / '+s.mag],['Reload',num(s.loadingSpeed)+' rounds/sec'],['Critical chance',percent(s.critChance)],['Shield',num(u.shield??s.shieldCapacity)],['Fighting range',Math.round(u.plan?.preferred??s.range)],['Orders',capacityFor(u)],['Shot interval',num(s.reload)+' sec'],['Critical multiplier',num(s.critMultiplier)+'×'],['Penetration',percent(s.penetration)],['Projectile speed',num(s.projectileSpeed)],['Splash radius',num(s.explosionRadius)],['Accuracy',num(s.accuracy)],['Splash falloff',percent(s.splashFalloff)],['Reload delay',num(s.reloadDelay)],['Reserve ammo',Math.round(u.reserve??s.ammoReserve)],['Heat',num(u.heat??0)+' / '+num(s.heatCapacity)],['Heat per shot',num(s.heatPerShot)],['Cooling',num(s.coolingRate)],['Shield recharge',num(s.shieldRecharge)],['Repair / sec',num(s.repairRate)],['Impact resistance',percent(s.impactResistance)],['Acceleration',num(s.acceleration)],['Braking',num(s.braking)],['Hull turn',num(s.turnRate)],['Turret turn',num(s.turretTurnRate)],['Reverse speed',num(s.reverseSpeed)],['Traction',num(s.terrainTraction)],['Radar',num(s.radarRange)],['Scan interval',num(s.scanInterval)],['Lock time',num(s.targetLockTime)],['Energy',num(u.energy??s.energyCapacity)+' / '+num(s.energyCapacity)],['Energy / sec',num(s.energyRegeneration)]]}
let tooltipPinned=false,tooltipTimer=null;function hideUnitTooltip(){if(tooltipTimer)clearTimeout(tooltipTimer);$('unitTooltip').hidden=true;tooltipPinned=false;window.unitTooltipId=null}
function showUnitTooltip(u,x,y,pinned=false){if(!u)return;if(tooltipTimer)clearTimeout(tooltipTimer);if(tooltipPinned&&!pinned)return;tooltipPinned=pinned;window.unitTooltipId=u.id;const tip=$('unitTooltip');$('tooltipName').textContent=(u.name||unitTypes[u.type].name)+' · '+unitTypes[u.type].name+' '+'★'.repeat(u.tier);$('tooltipStats').replaceChildren();$('tooltipMore').replaceChildren();for(const [i,[label,value]]of unitTooltipRows(u).entries()){const div=document.createElement('div'),small=document.createElement('small'),b=document.createElement('b');small.textContent=label;b.textContent=value;div.append(small,b);$(i<10?'tooltipStats':'tooltipMore').append(div)}tip.hidden=false;tip.style.left=Math.max(8,Math.min(x+350>innerWidth?x-350:x+14,innerWidth-350))+'px';tip.style.top=Math.max(8,Math.min(y+14,innerHeight-Math.min(tip.offsetHeight||350,innerHeight*.7)-8))+'px'}
function attachUnitTooltip(card,u){card.onpointerenter=e=>{if(e.pointerType!=='touch')showUnitTooltip(u,e.clientX,e.clientY)};card.onpointerleave=()=>{if(!tooltipPinned)tooltipTimer=setTimeout(hideUnitTooltip,150)};card.setAttribute('tabindex','0');card.onfocus=()=>showUnitTooltip(u,16,120)}
$('closeTooltip').onclick=hideUnitTooltip;$('unitTooltip').onpointerenter=()=>{if(tooltipTimer)clearTimeout(tooltipTimer)};$('unitTooltip').onpointerleave=()=>{if(!tooltipPinned)hideUnitTooltip()};window.unitInspector={show:showUnitTooltip,hide:()=>{if(!tooltipPinned)hideUnitTooltip()},dismiss:hideUnitTooltip};
const tooltipRoster=renderRoster;renderRoster=function(){tooltipRoster();for(const [i,card]of [...$('rosterGrid').children].entries()){attachUnitTooltip(card,roster[i]);card.onclick=e=>{if(e.target===card)showUnitTooltip(roster[i],e.clientX,e.clientY,true)}}};
function depotEdit(action){const prior=mode;if(inFieldBase&&mode==='won')mode='ready';try{return action()}finally{mode=prior}}
const depotSaveScript=$('saveScript').onclick;$('saveScript').onclick=()=>depotEdit(depotSaveScript);
const depotLoadout=renderLoadout;renderLoadout=function(){depotEdit(depotLoadout);if(inFieldBase)for(const b of $('loadoutDialog').querySelectorAll?.('button')||[]){const action=b.onclick;if(action)b.onclick=e=>depotEdit(()=>action(e))}};
const reportFire=squadFire;squadFire=function(t,target){const ammo=t.ammo;reportFire(t,target);if(t.ammo<ammo)t.reportShots=(t.reportShots||0)+1};
const reportHit=takeHit;takeHit=function(t,shot,scale=1){const before=t.hp+t.shield;reportHit(t,shot,scale);const loss=Math.max(0,before-t.hp-t.shield);t.reportDamageTaken=(t.reportDamageTaken||0)+loss;const source=battleUnits.find(u=>u.id===shot.owner);if(source){source.reportDamageDealt=(source.reportDamageDealt||0)+loss;if(loss>0)source.reportHits=(source.reportHits||0)+1}if(t.hp<=0&&before>0&&source)source.reportKills=(source.reportKills||0)+1};
const reportPickup=collectPickup;collectPickup=function(t,p){const before=p.used;reportPickup(t,p);if(!before&&p.used){t.reportPickups=t.reportPickups||{};t.reportPickups[p.kind]=(t.reportPickups[p.kind]||0)+1}};
function collectBattleReport(win){return{version:1,round,map:campaign.map,result:win?'victory':'defeat',durationSeconds:Math.round(elapsed*10)/10,units:battleUnits.map(t=>({id:t.id,side:t.team,type:t.type,tier:t.tier,callsign:callsign(t),survived:t.hp>0,remainingHealth:Math.ceil(t.hp),maximumHealth:t.maxHp,shotsFired:t.reportShots||0,damageDealt:Math.round(t.reportDamageDealt||0),damageTaken:Math.round(t.reportDamageTaken||0),hitEvents:t.reportHits||0,kills:t.reportKills||0,reserveAmmo:t.reserve,magazineAmmo:t.ammo,pickups:t.reportPickups||{}}))}}
let coachSettings={provider:'ollama',endpoint:'http://127.0.0.1:11434/api/chat',model:'qwen2.5-coder:3b',enabled:false,autoApply:false},coachApiKey='';try{const saved=JSON.parse(localStorage.getItem('tank-coach-preferences'));if(saved)coachSettings={...coachSettings,...saved,enabled:false,autoApply:false}}catch{}
function openCoachSettings(){for(const key of ['provider','endpoint','model'])$('coach'+key[0].toUpperCase()+key.slice(1)).value=coachSettings[key];$('coachEnabled').checked=coachSettings.enabled;$('coachAutoApply').checked=coachSettings.autoApply;$('coachKey').value=coachApiKey;$('coachReport').textContent=lastBattleReport?JSON.stringify(lastBattleReport,null,2):'Play a campaign battle first.';$('coachDialog').showModal()}
$('coachButton').onclick=openCoachSettings;$('closeCoach').onclick=()=>$('coachDialog').close();$('coachProvider').onchange=()=>{$('coachEndpoint').value=$('coachProvider').value==='ollama'?'http://127.0.0.1:11434/api/chat':''};
$('saveCoach').onclick=()=>{const endpoint=$('coachEndpoint').value.trim(),model=$('coachModel').value.trim();try{const url=new URL(endpoint);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('Use a valid HTTP endpoint without embedded credentials.');if(!model)throw Error('Enter your model name.');coachSettings={provider:$('coachProvider').value,endpoint,model,enabled:$('coachEnabled').checked,autoApply:$('coachAutoApply').checked};coachApiKey=$('coachKey').value.trim();localStorage.setItem('tank-coach-preferences',JSON.stringify({provider:coachSettings.provider,endpoint,model}));if(!coachSettings.enabled){coachGeneration++;if(coachRequest)coachRequest.abort();coachRequest=null;coachDraft=null;$('applyCoachDraft').hidden=true;$('coachDraftReview').hidden=true}renderBase();$('coachMessage').textContent=coachSettings.enabled?'Coach enabled for this session. Battle reports will be sent to '+new URL(endpoint).host+'.':'Coach is off. No reports will be sent.'}catch(e){$('coachMessage').textContent=e.message}};
function coachSnapshot(){return JSON.stringify({units:roster.map(u=>({id:u.id,script:u.unitScript})),squad:campaign.orders})}
function validateCoachDraft(data){if(!data||!Array.isArray(data.scripts)||data.scripts.length>15)throw Error('Coach must return one or more unit scripts.');const ids=new Set();for(const row of data.scripts){if(!roster.some(u=>u.id===row.id)||ids.has(row.id)||typeof row.script!=='string')throw Error('Coach returned an unknown or duplicate unit.');ids.add(row.id);const p=compilePython(row.script);if(p.errors.length)throw Error('Coach script rejected: '+p.errors.join(' · '))}if(data.squadScript!==undefined&&(typeof data.squadScript!=='string'||data.squadScript&&compilePython(data.squadScript).errors.length))throw Error('Coach squad script rejected.');return data}
async function requestCoach(){if(!coachSettings.enabled){$('coachMessage').textContent='Opt in and save the connection first.';return}if(!lastBattleReport||coachRequest){$('coachMessage').textContent=coachRequest?'Analysis is already running.':'Play a campaign battle first.';return}const controller=new AbortController(),generation=++coachGeneration,snapshot=coachSnapshot();coachAttemptedReport=lastBattleReport;coachRequest=controller;$('coachStatus').textContent='Coach is analyzing the battle…';$('coachMessage').textContent='Sending battle report to your chosen model…';renderBase();try{const units=roster.map(u=>({id:u.id,type:u.type,tier:u.tier,script:u.unitScript})),response=await fetch('/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...coachSettings,key:coachApiKey,report:lastBattleReport,units,squadScript:campaign.orders}),signal:controller.signal}),data=await response.json();if(!response.ok||data.error)throw Error(data.error||'Coach unavailable.');if(generation!==coachGeneration||!coachSettings.enabled)return;if(snapshot!==coachSnapshot())throw Error('Scripts changed during analysis. Run the coach again.');coachDraft=validateCoachDraft(data);coachDraft.snapshot=snapshot;$('coachStatus').textContent=(data.summary||'Coach returned valid script updates.').slice(0,400);$('coachMessage').textContent='Valid draft ready.';$('applyCoachDraft').hidden=false;$('coachDraftReview').hidden=false;$('coachDraftText').textContent=data.scripts.map(row=>(roster.find(u=>u.id===row.id)?.name||row.id)+'\n'+row.script).join('\n\n')+(data.squadScript!==undefined?'\n\nSquad script\n'+data.squadScript:'');if(coachSettings.autoApply)applyCoachScripts()}catch(e){if(generation===coachGeneration){$('coachStatus').textContent=e.name==='AbortError'?'Coach analysis cancelled.':e.message;$('coachMessage').textContent=$('coachStatus').textContent}}finally{if(coachRequest===controller)coachRequest=null;renderBase()}}
function applyCoachScripts(){if(!coachDraft||mode==='running'||coachSnapshot()!==coachDraft.snapshot){$('coachStatus').textContent='Draft is stale or a battle is running. Analyze again between battles.';return}const draft=validateCoachDraft(coachDraft);for(const row of draft.scripts)roster.find(u=>u.id===row.id).unitScript=row.script;if(draft.squadScript!==undefined){campaign.orders=draft.squadScript;squadScript=draft.squadScript;$('prompt').value=squadScript}saveProgram();preview();coachDraft=null;$('applyCoachDraft').hidden=true;$('coachDraftReview').hidden=true;$('coachStatus').textContent='Validated coach scripts applied. Ready for your next battle.'}
$('applyCoachDraft').onclick=applyCoachScripts;$('runCoach').onclick=()=>requestCoach();
