import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import worker from '../dist/server/index.js';
const sqlite=new DatabaseSync(':memory:');for(const n of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+n,'utf8'));
const DB={prepare(sql){const stmt=sqlite.prepare(sql);const methods=args=>({async first(){return stmt.get(...args)||null},async all(){return{results:stmt.all(...args)}},async run(){const r=stmt.run(...args);return{meta:{changes:r.changes}}}});return{bind(...args){return methods(args)},...methods([])}}};DB.batch=async statements=>{sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}};
async function api(path,method='GET',body=null,token=null){const r=await worker.fetch(new Request('https://game.example'+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(token?{'x-match-token':token}:{})},...(body?{body:JSON.stringify(body)}:{})}),{DB});return{status:r.status,body:await r.json()}}
const a=(await api('/api/matches/profile','POST',{name:'A'})).body,b=(await api('/api/matches/profile','POST',{name:'B'})).body;assert.equal(a.account.roster.length,1);assert.equal(a.account.credits,0);assert.equal(a.account.roster[0].type,'tank');
for(const key of ['units','credits','slots','upgrades','winner','reward','resources'])assert.equal((await api('/api/matches/profile','POST',{profile:a.profile,[key]:999})).status,400);
assert.equal((await api('/api/matches/profile','POST',{profile:{...a.profile,token:'bad'}})).status,400);
assert.equal((await api('/api/matches/profile','POST',{profile:a.profile,scripts:[{id:'not-owned',unitScript:a.account.roster[0].unitScript}]})).status,400);
assert.equal((await api('/api/matches/profile','POST',{profile:a.profile,scripts:[{id:'online-1',unitScript:'def tick(unit, squad):\n    unit.hp = 9999'}]})).status,400);
assert.equal((await api('/api/matches/shop','POST',{profile:a.profile,item:'slot',price:0})).status,400);
const invite=(await api('/api/matches/create','POST',{profile:a.profile})).body;assert.equal(invite.status,'waiting');assert.equal((await api('/api/matches/create','POST',{profile:a.profile})).status,400);
const joined=(await api('/api/matches/join','POST',{profile:b.profile,code:invite.code})).body;assert.equal(joined.status,'running');assert.notEqual(joined.token,invite.token);
assert.equal((await api('/api/matches?code='+invite.code,'GET',null,'bad')).status,403);
const live=(await api('/api/matches?code='+invite.code,'GET',null,invite.token)).body;assert.equal(live.battleUnits.length,2);
sqlite.prepare('UPDATE arena_matches SET state=? WHERE code=?').run(JSON.stringify({...live,mode:'won'}),invite.code);
await api('/api/matches?code='+invite.code,'GET',null,invite.token);await api('/api/matches?code='+invite.code,'GET',null,invite.token);
const rewarded=(await api('/api/matches/profile','POST',{profile:a.profile})).body,loser=(await api('/api/matches/profile','POST',{profile:b.profile})).body;assert.equal(rewarded.account.credits,60);assert.equal(loser.account.credits,15);
const bought=(await api('/api/matches/shop','POST',{profile:a.profile,item:'gear:weapon-0'})).body;assert.equal(bought.account.credits,0);assert.deepEqual(bought.account.gear,['weapon-0']);
assert.equal((await api('/api/matches/shop','POST',{profile:a.profile,item:'equip:online-1:armor-0'})).status,400);
const equipped=(await api('/api/matches/shop','POST',{profile:a.profile,item:'equip:online-1:weapon-0'})).body;assert.equal(equipped.account.roster[0].equipment.weapon,'weapon-0');
const board=(await api('/api/matches/leaderboard')).body;assert.equal(board.players[0].wins,1);assert.ok(!JSON.stringify(board).includes(a.profile.token));
assert.equal((await api('/api/matches/random','POST',{profile:a.profile})).body.status,'running');
console.log('Server-owned units/resources, Python validation, token access, authoritative matches, idempotent payouts, owned equipment and leaderboard passed.');
