import assert from 'node:assert/strict';import {coachEndpoint,generateCoach,validateCoachResponse} from './coach.mjs';
const script='def tick(unit, squad):\n    unit.focus("nearest")\n    unit.hold_range(255)',units=[{id:'owned-1',type:'tank',tier:1,script}],input={provider:'ollama',endpoint:'http://127.0.0.1:11434/api/chat',model:'test-model',key:'',enabled:true,units,squadScript:'',report:{round:1,map:'urban',result:'defeat',durationSeconds:40,apiKey:'never-forward',units:[{id:'owned-1',side:'player',type:'tank',tier:1,callsign:'tank-1',shotsFired:8,damageDealt:100,damageTaken:160,pickups:{health:1}}]}};
let forwarded=null;const fake=async(url,opts)=>{forwarded={url,opts,body:JSON.parse(opts.body)};return new Response(JSON.stringify({message:{content:JSON.stringify({scripts:[{id:'owned-1',script}],summary:'Preserve range and use cover.'})}}))};
const draft=await generateCoach(input,{fetch:fake,reference:'Reference fixture'});assert.equal(draft.scripts[0].script,script);assert.equal(forwarded.body.format.type,'object');assert.equal(forwarded.opts.redirect,'error');assert.ok(!forwarded.body.messages[1].content.includes('never-forward'));assert.ok(!forwarded.opts.headers.authorization);
const provider=async(url,opts)=>{forwarded={url,opts};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({scripts:[{id:'owned-1',script}],summary:'Valid provider reply'})}}]}))};await generateCoach({...input,provider:'compatible',endpoint:'https://provider.example/v1/chat/completions',key:'test-only-key'},{fetch:provider,reference:'Reference'});assert.equal(forwarded.opts.headers.authorization,'Bearer test-only-key');assert.ok(!forwarded.opts.body.includes('test-only-key'));
await assert.rejects(()=>generateCoach({...input,enabled:false},{fetch:()=>{throw Error('Must never fetch')}}),/opt-in/);
for(const endpoint of ['http://provider.example/v1/chat/completions','https://user:password@provider.example/v1/chat/completions','https://provider.example/v1/chat/completions?key=secret','file:///tmp/chat/completions'])assert.throws(()=>coachEndpoint({...input,provider:'compatible',endpoint}));
await assert.rejects(()=>generateCoach(input,{fetch:async()=>new Response('Unauthorized',{status:401}),reference:'Reference'}),/HTTP 401/);
assert.throws(()=>validateCoachResponse({scripts:[{id:'not-owned',script}]},units),/unknown/);assert.throws(()=>validateCoachResponse({scripts:[{id:'owned-1',script:'def tick(unit, squad):\n    unit.hp = 100000'}]},units));assert.throws(()=>validateCoachResponse({scripts:[{id:'owned-1',script}],credits:99999},units));
console.log('Coach opt-in, endpoint rules, credential isolation, report sanitization, provider protocols, error handling and Python response validation passed.');
for(const kind of ['gemini','openai']){const reply={scripts:[],squadScript:null,summary:'No change justified'},endpoint=kind==='gemini'?'https://generativelanguage.googleapis.com/v1beta':'https://api.openai.com/v1/responses';const cloudFake=async(url,opts)=>{forwarded={url,opts,body:JSON.parse(opts.body)};return new Response(JSON.stringify(kind==='gemini'?{candidates:[{content:{parts:[{text:JSON.stringify(reply)}]}}]}:{output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(reply)}]}]}))};const result=await generateCoach({...input,provider:kind,endpoint,model:'test-model',key:'fixture-key'},{fetch:cloudFake});assert.equal(result.scripts.length,0);assert.ok(result.documentation.characters>10000);assert.ok(forwarded.opts.body.includes('unit.seek_health'));assert.ok(!forwarded.opts.body.includes('fixture-key'));if(kind==='gemini'){assert.equal(forwarded.opts.headers['x-goog-api-key'],'fixture-key');assert.ok(forwarded.url.endsWith('/models/test-model:generateContent'));assert.equal(forwarded.body.generationConfig.responseMimeType,'application/json')}else{assert.equal(forwarded.opts.headers.authorization,'Bearer fixture-key');assert.equal(forwarded.body.store,false);assert.equal(forwarded.body.text.format.strict,true);assert.ok(forwarded.body.text.format.schema.required.includes('squadScript'))}assert.throws(()=>coachEndpoint({...input,provider:kind,endpoint:'https://other.example/v1/responses',model:'test'}))}
console.log('Native Gemini/OpenAI formats, full real reference, key isolation and no-change replies passed.');
let retryCalls=0;await generateCoach(input,{reference:'Fixture',fetch:async()=>++retryCalls===1?new Response('Runner warming',{status:500}):new Response(JSON.stringify({message:{content:JSON.stringify({scripts:[],summary:'No change'})}}))});assert.equal(retryCalls,2);
let hostedCalls=0;await assert.rejects(()=>generateCoach({...input,provider:'openai',endpoint:'https://api.openai.com/v1/responses',key:'fixture'},{reference:'Fixture',fetch:async()=>{hostedCalls++;return new Response('Failure',{status:500})}}),/HTTP 500/);assert.equal(hostedCalls,1);
console.log('One local startup retry and no automatic hosted retries passed.');
