import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
const rooms=new Map();
const types=['tank','infantry','helicopter','rocket','artillery','sniper','boat'];
const commandIds=['radar','gun','drive','cover','duck','perch','retreat'];
function node(){return {textContent:'',value:'',style:{},children:[],classList:{remove(){},toggle(){}},replaceChildren(){this.children=[]},append(...n){this.children.push(...n)},setAttribute(){},addEventListener(){},showModal(){},close(){},querySelector(){return null}}}
function sanitizeSquad(units,prefix){if(!Array.isArray(units)||!units.length||units.length>15)throw Error('Submit 1–15 units');return units.map((u,i)=>{if(!types.includes(u.type)||!Number.isInteger(u.tier)||u.tier<1||u.tier>3||typeof u.instruction!=='string'||u.instruction.length>2000)throw Error('Invalid unit');const equipment={};for(const slot of ['weapon','armor','utility'])if(new RegExp('^'+slot+'-[0-9]$').test(u.equipment?.[slot]||''))equipment[slot]=u.equipment[slot];let compiled=null;if(u.compiled&&['rush','balanced','sniper'].includes(u.compiled.style)&&['always','inRange','stationary'].includes(u.compiled.firePolicy)){const p=u.compiled;compiled={style:p.style,preferred:Math.max(100,Math.min(500,Number(p.preferred)||255)),cover:!!p.cover,evade:!!p.evade,retreat:!!p.retreat,coverBelow:Math.max(0,Math.min(.9,Number(p.coverBelow)||.5)),retreatBelow:Math.max(0,Math.min(.8,Number(p.retreatBelow)||.25)),firePolicy:p.firePolicy,explanation:''}}return{id:prefix+i,type:u.type,tier:u.tier,instruction:u.instruction,squadScript:typeof u.squadScript==='string'&&u.squadScript.length<=3000?u.squadScript:'leader tank-1\nall focus nearest\nall follow leader',commands:Array.isArray(u.commands)?u.commands.filter(c=>commandIds.slice(0,u.tier===1?3:u.tier===2?5:7).includes(c)):['radar','gun','drive'],equipment,compiled,compiledText:u.instruction}})}
function buildEngine(room){const elements=new Map();const document={getElementById(id){if(!elements.has(id))elements.set(id,node());return elements.get(id)},createElement:node,querySelectorAll(){return []}};const canvas=document.getElementById('arena');canvas.width=920;canvas.height=560;canvas.getContext=()=>({});const storage=new Map();const context=vm.createContext({document,window:{},setTimeout,clearTimeout,performance:{now:()=>0},requestAnimationFrame(){},confirm:()=>false,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},AbortSignal,fetch:async()=>{throw Error('no model in match service')},Math,console});const source=readFileSync(new URL('../dist/play.html',import.meta.url),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];vm.runInContext(source,context,{timeout:5000});const [a,b]=room.players;vm.runInContext(`roster=${JSON.stringify(a.units)};squadScript=roster[0].squadScript||defaultSquadScript;selectedId=roster[0].id;campaign.map=${JSON.stringify(room.map)};round=1;commands=new Set(roster[0].commands);$('prompt').value=roster[0].instruction;compiledPlan=roster[0].compiled;compiledText=roster[0].instruction;resetPositions();battleUnits=battleUnits.filter(u=>u.team==='player');const opponents=${JSON.stringify(b.units)};for(let i=0;i<opponents.length;i++){const t=spawnCombat(opponents[i],'player',i,opponents.length);t.team='enemy';t.x=840-Math.floor(i/6)*55;t.angle=Math.PI;t.heading=Math.PI;t.plan=planForUnit(opponents[i]);t.commands=opponents[i].commands.filter(c=>unlocked(opponents[i]).includes(c));battleUnits.push(t)}enemy=battleUnits.find(u=>u.team==='enemy');seed=${room.seed};mode='running';finish=function(win){mode=win?'won':'lost'};`,context,{timeout:5000});return context}
function snapshot(room,token){const seat=room.players.findIndex(p=>p.token===token);if(seat<0)throw Error('Invalid session token');if(!room.engine)return{code:room.code,status:'waiting',seat};const state=JSON.parse(vm.runInContext('JSON.stringify({mode,elapsed,battleUnits,shots,sparks},(key,value)=>key==="target"?undefined:value)',room.engine));return{code:room.code,seat,status:state.mode==='running'?'running':'finished',winner:state.mode==='won'?0:1,seed:room.seed,map:room.map,...state}}
export async function matchRequest(req,url){if(!url.pathname.startsWith('/api/matches'))return null;const token=req.headers['x-match-token'];if(req.method==='GET'){const room=rooms.get(url.searchParams.get('code'));if(!room)throw Error('Match expired or not found');return snapshot(room,token)}let raw='';for await(const c of req){raw+=c;if(raw.length>120000)throw Error('Squad too large')}const body=JSON.parse(raw||'{}');if(req.method!=='POST')throw Error('Unsupported match action');if(url.pathname==='/api/matches/create'){if(rooms.size>=32)throw Error('Match service busy');const code=randomBytes(3).toString('hex').toUpperCase(),token=randomBytes(24).toString('hex');const room={code,seed:randomBytes(4).readUInt32LE(),map:['urban','canyon','volcanic','coast'].includes(body.map)?body.map:'urban',players:[{token,units:sanitizeSquad(body.units,'a-')}],created:Date.now(),engine:null};rooms.set(code,room);return{code,token,status:'waiting',seat:0}}if(url.pathname==='/api/matches/join'){const room=rooms.get(String(body.code||'').toUpperCase());if(!room)throw Error('Match not found');if(room.players.length>=2)throw Error('Match already has two players');const token=randomBytes(24).toString('hex');room.players.push({token,units:sanitizeSquad(body.units,'b-')});try{room.engine=buildEngine(room)}catch(e){room.players.pop();throw e}return{code:room.code,token,status:'running',seat:1}}throw Error('Unknown match action')}
const ticker=setInterval(()=>{for(const [code,room] of rooms){if(Date.now()-room.created>15*60*1000){rooms.delete(code);continue}if(!room.engine)continue;try{vm.runInContext("if(mode==='running')for(let i=0;i<6&&mode==='running';i++)update(1/60)",room.engine,{timeout:1000})}catch(e){room.engine=null;console.error('Match failed:',e.message)}}},100);ticker.unref();

