import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {createEngine} from '../dist/server/engine.mjs';import {validatePython} from '../cloud/python-policy.mjs';
const doc=fs.readFileSync('docs/SQUADSCRIPT.md','utf8'),examples=[...doc.matchAll(/```python\n([\s\S]*?)```/g)].map(m=>m[1].trim());
for(const sample of examples)assert.equal(validatePython(sample),sample);
for(const body of ['unit.hp = 9999','squad.credits = 9999','unit.add_unit("tank")','unit.__class__()','import os','while True:\n        unit.stop()','unit.stop(1)','unit.focus()','exec("bad")'])assert.throws(()=>validatePython('def tick(unit, squad):\n    '+body));
const basic='def tick(unit, squad):\n    unit.focus("nearest")\n    unit.hold_range(255)',u={id:'test',type:'tank',tier:1,unitScript:basic,squadScript:basic,commands:['radar','gun','drive'],equipment:{}};
const engine=createEngine([{...u,unitScript:'def tick(unit, squad):\n    low = unit.hp_ratio < 0.5\n    if not low:\n        unit.hold_fire()\n        unit.stop()\n    else:\n        unit.fire_at_will()'}],[{...u,id:'enemy'}],'urban',123);
engine.tick(1);const state=engine.state(),tank=state.battleUnits[0];assert.ok(tank.activeFunctions.includes('hold-fire'));assert.ok(tank.activeFunctions.includes('stop'));assert.equal(state.shots.filter(s=>s.team==='player').length,0);
const parser=vm.runInNewContext(fs.readFileSync('client/python-parser.js','utf8')+';PythonUnit');const p=parser.compile('def tick(unit, squad):\n    n = 2 + 3 * 4\n    if n == 14 and not unit.hp_ratio < 0.5:\n        unit.stop()\n    elif unit.hp_ratio < 0.2:\n        unit.withdraw()\n    else:\n        unit.advance()',new Set(['stop','withdraw','advance']),new Set(['unit.hp_ratio']),new Set());assert.equal(p.errors.length,0);let actions=[];parser.execute(p,{'unit.hp_ratio':1},()=>0,n=>actions.push(n));assert.equal(actions.join(), 'stop');actions=[];parser.execute(p,{'unit.hp_ratio':.1},()=>0,n=>actions.push(n));assert.equal(actions.join(),'withdraw');
const layouts=[];for(const map of ['urban','canyon','volcanic','coast']){const e=createEngine([u],[{...u,id:'b'}],map,12),s=e.state();assert.ok(s.buildings.length>15);layouts.push(JSON.stringify(s.buildings.map(b=>[b.x,b.y,b.kind])))}assert.equal(new Set(layouts).size,4);
const priority='def tick(unit, squad):\n    unit.focus_armor()\n    unit.focus_air()',enemies=[{...u,id:'ground'},{...u,id:'air',type:'helicopter'}],initial=createEngine([{...u,unitScript:priority}],enemies,'urban',5).state();initial.battleUnits.forEach((t,i)=>{t.x=500+i*30;t.y=500;t.scan=0});const targeted=createEngine([{...u,unitScript:priority}],enemies,'urban',5,initial);targeted.tick(.1);assert.equal(targeted.state().battleUnits[0].targetId,'air');
for(const [condition,hp,expected]of [['0.25 < unit.hp_ratio < 0.75',.5,'stop'],['0.25 < unit.hp_ratio < 0.75',.1,'advance'],['0.25 < unit.hp_ratio < 0.75',.9,'advance'],['not 0.25 < unit.hp_ratio < 0.75',.5,'advance'],['0 < unit.hp_ratio <= 0.5 and unit.hp_ratio != 0',.5,'stop']]){const program=parser.compile('def tick(unit, squad):\n    if '+condition+':\n        unit.stop()\n    else:\n        unit.advance()',new Set(['stop','advance']),new Set(['unit.hp_ratio']),new Set());assert.equal(program.errors.length,0);const issued=[];parser.execute(program,{'unit.hp_ratio':hp},()=>0,n=>issued.push(n));assert.equal(issued.join(),expected)}
for(const action of ['unit.focus("closest")','unit.hold_range("255")','unit.protect("tank-0")','unit.follow("healer-1")','unit.focus(123)'])assert.throws(()=>validatePython('def tick(unit, squad):\n    '+action));
for(const query of ['unit.map_is("desert")','unit.is_type("dragon")','unit.can_afford("free")','unit.ally_alive(1)','unit.ability_ready("spawn_tank")'])assert.throws(()=>validatePython('def tick(unit, squad):\n    if '+query+':\n        unit.stop()'));
let reads=0;const short=parser.compile('def tick(unit, squad):\n    if 0.25 < unit.enemy_health() < 0.75:\n        unit.stop()\n    else:\n        unit.advance()',new Set(['stop','advance']),new Set(),new Set(['unit.enemy_health']));parser.execute(short,{},()=>{reads++;return .5},()=>{});assert.equal(reads,1);
console.log('Python examples, comparison chains, literal argument validation, target priority, injection rejection and distinct maps passed.');
