import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync('dist/play.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const nodes=new Map(),timers=[];
const node=()=>({value:'',checked:false,style:{},children:[],classList:{remove(){},toggle(){}},replaceChildren(){this.children=[]},append(...x){this.children.push(...x)},addEventListener(){},setAttribute(){},showModal(){},close(){},querySelector(){return{focus(){}}}});
const document={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},createElement:node,querySelectorAll(){return[]}};Object.assign(document.getElementById('arena'),{width:920,height:560,getContext:()=>({})});
const context=vm.createContext({document,window:{},localStorage:{getItem:()=>null,setItem(){},removeItem(){}},performance:{now:()=>0},requestAnimationFrame(){},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){},Math,console,fetch:async()=>{throw Error('offline')},confirm:()=>true});const run=text=>vm.runInContext(text,context);run(source);
assert.equal(run('squadFunctions.length'),78);assert.equal(run('new Set(squadFunctions.map(f=>f.name)).size'),78);assert.equal(run('Object.keys(unitTypes).length'),10);
run(String.raw`for(const f of squadFunctions){const type=groupType(f.group)||'tank';const parsed=parseSquadScript(type+' '+f.name+' when hp below 70%');if(parsed.errors.length||parsed.rules.length!==1)throw Error('Function parser failed '+f.name);round=10;const t=spawnCombat({id:'probe',type,tier:3,equipment:{}},'player',0,1),foe=spawnCombat({id:'foe',type:f.name==='depth-charge'?'boat':'tank',tier:1,equipment:{}},'enemy',0,1),ally=spawnCombat({id:'ally',type:f.name==='triage'?'infantry':'tank',tier:1,equipment:{}},'player',1,2);t.x=500;t.y=500;t.homeX=460;t.homeY=450;t.hp=t.maxHp*.5;t.ammo=1;t.reserve=10;t.heat=70;t.cooldown=1;t.phase=1;t.target=foe;foe.x=540;foe.y=500;ally.x=480;ally.y=500;ally.hp=30;ally.reserve=5;t.squadScript=type+' '+f.name;battleUnits=[t,foe,ally];rocks.splice(0,rocks.length);pickups=[{kind:'health',x:550,y:500,used:false},{kind:'ammo',x:450,y:500,used:false},{kind:'shield',x:500,y:550,used:false},{kind:'overdrive',x:500,y:450,used:false}];elapsed=20;shots=[{x:520,y:500,vx:-100,vy:10,team:'enemy'}];squadTick(t,1/60);const motion=functionMotion(t,foe);if(!t.activeFunctions.includes(f.name)||!Number.isFinite(t.x)||!Number.isFinite(t.stats.damage)||motion&&(!Number.isFinite(motion.mx)||!Number.isFinite(motion.my)))throw Error('Invalid execution '+f.name);}`);
run(String.raw`if(!parseSquadScript('infantry brace').errors.length||!parseSquadScript('all eval malicious').errors.length||!parseSquadScript('tank brace when hp below 150%').errors.length)throw Error('Unsafe/invalid scripts accepted');round=1;resetPositions();const t=player;t.squadScript='all advance\nall stop\nall kite\nall brace';t.hp=t.maxHp;t.tier=1;squadTick(t,.01);if(activeFunction(t,'advance')||!activeFunction(t,'brace'))throw Error('Latest 3 orders must take priority');t.squadScript='all brace when hp below 50%';t.hp=t.maxHp;squadTick(t,.01);if(activeFunction(t,'brace'))throw Error('Inactive condition ran');t.hp=40;squadTick(t,.01);if(!activeFunction(t,'brace'))throw Error('Active condition ignored');`);
run(String.raw`round=1;resetPositions();const damage=unitStats({type:'tank',tier:1,equipment:{}}).damage;if(Math.abs(enemy.stats.damage-damage*.8)>.001||enemy.hp!==120)throw Error('AI reduction must be 20%, retaining Round 1 HP');for(round=1;round<6;round++){if(availableTypes().includes('helicopter'))throw Error('Air unlock too early');resetPositions();if(battleUnits.some(t=>t.type==='helicopter'))throw Error('Early helicopter opponent');if(battleUnits.filter(t=>t.team==='enemy').length!==1+Math.floor((round-1)/4))throw Error('Enemy count scaling wrong')}round=6;if(!availableTypes().includes('helicopter')||unitTypes.helicopter.hp!==70)throw Error('Fragile Round 6 helicopter missing');`);
// Support effects and cooldowns are checked independently of their visual flash.
run(String.raw`round=10;const medic=spawnCombat({id:'m',type:'medic',tier:1,equipment:{}},'player',0,1),patient=spawnCombat({id:'p',type:'infantry',tier:1,equipment:{}},'player',1,2);medic.x=patient.x=300;medic.y=patient.y=300;patient.hp=20;medic.squadScript='medic triage';battleUnits=[medic,patient];elapsed=30;squadTick(medic,.01);if(patient.hp!==45)throw Error('Triage must heal 25');squadTick(medic,.01);if(patient.hp!==45)throw Error('Triage cooldown missing');const scout=spawnCombat({id:'s',type:'scout',tier:1,equipment:{}},'player',0,1),foe=spawnCombat({id:'e',type:'tank',tier:1,equipment:{}},'enemy',0,1);scout.x=300;scout.y=300;foe.x=340;foe.y=300;scout.squadScript='scout mark';battleUnits=[scout,foe];squadTick(scout,.01);if(foe.markedUntil!==34||foe.markedBy!=='player')throw Error('Mark must tag target');`);
run(String.raw`round=1;mode='ready';resetRun();autoRestart=true;mode='running';finish(false);if(mode!=='lost'||campaign.lives!==2)throw Error('Defeat should spend a life');`);
timers.at(-1)();assert.equal(run('mode'),'running');run(String.raw`autoRestart=false;mode='running';finish(false)`);assert.equal(run('mode'),'lost');
run(String.raw`{round=10;const t=spawnCombat({id:'slots',type:'tank',tier:1,equipment:{}},'player',0,1);battleUnits=[t];t.squadScript='all advance\nall kite\nall brace\nall retreat below 25%';if(!ordersFor(t)['ability:advance'])throw Error('Locked retreat consumed a slot');t.tier=3;if(!ordersFor(t).retreat)throw Error('Upgraded retreat missing')}
{const boat=spawnCombat({id:'boat',type:'boat',tier:1,equipment:{}},'player',0,1),land=spawnCombat({id:'land',type:'tank',tier:1,equipment:{}},'enemy',0,1),naval=spawnCombat({id:'naval',type:'boat',tier:1,equipment:{}},'enemy',1,2);boat.x=500;boat.y=land.y=naval.y=H*.76;land.x=510;naval.x=550;boat.target=land;boat.squadScript='boat depth-charge';battleUnits=[boat,land,naval];elapsed=100;const before=naval.hp;squadTick(boat,.01);if(naval.hp>=before||boat.abilityTimers['depth-charge']!==108)throw Error('Depth charge ignored naval target');boat.abilityTimers={};naval.hp=0;const energy=boat.energy;squadTick(boat,.01);if(boat.abilityTimers['depth-charge']||boat.energy<energy)throw Error('Depth charge wasted energy without boats')}
`);

console.log('Locked command slots, naval ability targeting passed.');

run(String.raw`{round=10;rocks.splice(0,rocks.length);for(const [type,fn] of [['tank','stop'],['helicopter','hover'],['sniper','steady'],['artillery','siege'],['medic','field-hospital']]){const t=spawnCombat({id:'stationary',type,tier:2,equipment:{}},'player',0,1),foe=spawnCombat({id:'foe',type:'tank',tier:1,equipment:{}},'enemy',0,1);t.x=500;t.y=500;foe.x=700;foe.y=500;t.target=foe;t.scan=100;t.basePlan={...t.plan,evade:true,cover:false};t.squadScript=type+' '+fn+'\nall zigzag';battleUnits=[t,foe];for(let i=0;i<120;i++){elapsed=200+i/60;squadTick(t,1/60)}if(t.x!==500||t.y!==500)throw Error(fn+' drifted despite stationary orders');t.squadScript=type+' '+fn+'\nall advance';squadTick(t,.1);if(t.x===500&&t.y===500)throw Error('Later advance did not replace '+fn);t.x=500;t.y=500;t.tier=3;t.hp=t.maxHp*.1;t.squadScript=type+' '+fn+'\nall retreat below 25%';squadTick(t,.1);if(t.x===500&&t.y===500)throw Error('Emergency retreat failed for '+fn)}}`);
console.log('All five stationary functions hold upgraded units still; later movement and emergency retreat passed.');
