// Deliberately bounded Python syntax, interpreted as an AST without eval/Function.
const PythonUnit=(()=>{
 const cache=new Map();
 function expression(source){const tokens=[];let i=0;while(i<source.length){if(/\s/.test(source[i])){i++;continue}const part=source.slice(i),m=part.match(/^(?:\d+(?:\.\d+)?|[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)?|"[^"\\]*"|'[^'\\]*'|==|!=|<=|>=|[<>+*/%(),-])/);if(!m)throw Error('Unsupported expression near '+part);tokens.push(m[0]);i+=m[0].length}let at=0;
  const precedence={or:1,and:2,'==':3,'!=':3,'<':3,'>':3,'<=':3,'>=':3,'+':4,'-':4,'*':5,'/':5,'%':5};
  function atom(){const token=tokens[at++];if(!token)throw Error('Expected a value');if(token==='not'||token==='-')return{op:token==='not'?'not':'neg',value:token==='not'?parse(3):atom()};if(token==='('){const value=parse(0);if(tokens[at++]!==')')throw Error('Missing closing parenthesis');return value}if(/^\d/.test(token))return{literal:Number(token)};if(/^['"]/.test(token))return{literal:token.slice(1,-1)};if(token==='True'||token==='False')return{literal:token==='True'};if(!/^[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)?$/.test(token)||token.includes('__'))throw Error('Unsupported value '+token);if(tokens[at]==='('){at++;const args=[];if(tokens[at]!==')')do{args.push(parse(0));if(tokens[at]!==',')break;at++}while(true);if(tokens[at++]!==')')throw Error('Missing closing parenthesis');return{call:token,args}}return{name:token}}
  function parse(min){let left=atom();while(precedence[tokens[at]]>=min){const op=tokens[at++],right=parse(precedence[op]+1);left={op,left,right}}return left}const tree=parse(0);if(at!==tokens.length)throw Error('Unexpected expression token');return tree;
 }
 function compile(text,methods,sensors,queries){if(cache.has(text))return cache.get(text);const errors=[],body=[],names=new Set(),calls=[];try{if(typeof text!=='string'||text.length>3000)throw Error('Python scripts are limited to 3000 characters');const lines=text.split('\n').map((raw,i)=>{if(raw.includes('\t'))throw Error('Use spaces, not tabs (line '+(i+1)+')');const clean=raw.replace(/\s+#.*$/,'').trimEnd();return{indent:clean.length-clean.trimStart().length,text:clean.trim(),line:i+1}}).filter(l=>l.text&&!l.text.startsWith('#'));if(lines.length>120)throw Error('Limit: 120 nonempty lines');if(lines[0]?.text!=='def tick(unit, squad):'||lines[0].indent!==0)throw Error('Begin with def tick(unit, squad):');let cursor=1;
   function checkExpr(tree){if(tree.name){if(tree.name.includes('.')){if(!sensors.has(tree.name))throw Error('Unknown read-only sensor '+tree.name)}else if(!names.has(tree.name))throw Error('Unknown local variable '+tree.name)}if(tree.call){if(!queries.has(tree.call))throw Error('Unknown sensor function '+tree.call);const zero=new Set(['unit.health_drop_distance','unit.ammo_drop_distance','unit.shield_drop_distance','unit.boost_drop_distance','unit.nearest_cover_distance','unit.enemy_shield','unit.enemy_health','unit.has_ammo','unit.can_fire']);const expected=zero.has(tree.call)?0:1;if(tree.args.length!==expected)throw Error(tree.call+' needs '+expected+' arguments');for(const a of tree.args)checkExpr(a)}if(tree.value)checkExpr(tree.value);if(tree.left)checkExpr(tree.left);if(tree.right)checkExpr(tree.right)}
   function value(source){const ast=expression(source);checkExpr(ast);return ast}
   function block(indent,depth){if(depth>6)throw Error('Maximum condition nesting is six');const result=[];while(cursor<lines.length&&lines[cursor].indent>=indent){const line=lines[cursor];if(line.indent!==indent)throw Error('Use four-space indentation at line '+line.line);cursor++;if(line.text==='return'){result.push({kind:'return'});continue}if(line.text==='pass'){result.push({kind:'pass'});continue}const condition=line.text.match(/^if (.+):$/);if(condition){const branches=[{test:value(condition[1]),body:block(indent+4,depth+1)}];if(!branches[0].body.length)throw Error('An if block needs a body');while(cursor<lines.length&&lines[cursor].indent===indent&&/^elif |^else:/.test(lines[cursor].text)){const next=lines[cursor++],elif=next.text.match(/^elif (.+):$/);if(!elif&&next.text!=='else:')throw Error('Invalid else');branches.push({test:elif?value(elif[1]):null,body:block(indent+4,depth+1)});if(!branches.at(-1).body.length)throw Error('Empty condition block');if(!elif)break}result.push({kind:'if',branches});continue}const assignment=line.text.match(/^([a-z][a-z0-9_]*) = (.+)$/);if(assignment){if(['unit','squad'].includes(assignment[1])||assignment[1].includes('__'))throw Error('Cannot replace game objects');const ast=value(assignment[2]);names.add(assignment[1]);result.push({kind:'assign',name:assignment[1],value:ast});continue}const action=line.text.match(/^unit\.([a-z][a-z0-9_]*)\((.*)\)$/);if(!action||!methods.has(action[1]))throw Error('Unknown action at line '+line.line+': '+line.text);const ast=expression('unit.'+action[1]+'('+action[2]+')');const count=action[1]==='move_to'?2:['hold_range','focus','follow','protect','flank','stance','retreat_below'].includes(action[1])?1:0;if(ast.args.length!==count)throw Error(action[1]+' needs '+count+' arguments');for(const a of ast.args)checkExpr(a);calls.push(action[1]);result.push({kind:'action',method:action[1],args:ast.args})}return result}
   body.push(...block(4,0));if(cursor!==lines.length)throw Error('Only tick() is allowed at the top level');if(!calls.length)throw Error('Include at least one unit action');
  }catch(e){errors.push(e.message)}const result={body,errors,calls};if(cache.size>200)cache.clear();cache.set(text,result);return result}
 function execute(program,env,query,action){const locals=Object.create(null);let budget=240;function read(ast){if(--budget<0)throw Error('Script instruction budget exceeded');if(Object.hasOwn(ast,'literal'))return ast.literal;if(ast.name)return ast.name.includes('.')?env[ast.name]:locals[ast.name];if(ast.call)return query(ast.call,ast.args.map(read));if(ast.op==='not')return!read(ast.value);if(ast.op==='neg')return-read(ast.value);const a=read(ast.left);if(ast.op==='and')return a&&read(ast.right);if(ast.op==='or')return a||read(ast.right);const b=read(ast.right);switch(ast.op){case'==':return a===b;case'!=':return a!==b;case'<':return a<b;case'>':return a>b;case'<=':return a<=b;case'>=':return a>=b;case'+':return Number(a)+Number(b);case'-':return a-b;case'*':return a*b;case'/':return b?a/b:0;case'%':return b?a%b:0}}function block(body){for(const node of body){if(--budget<0)throw Error('Script instruction budget exceeded');if(node.kind==='return')return true;if(node.kind==='assign')locals[node.name]=read(node.value);if(node.kind==='action')action(node.method,node.args.map(read));if(node.kind==='if'){for(const branch of node.branches)if(branch.test===null||read(branch.test)){if(block(branch.body))return true;break}}}return false}block(program.body)}
 return{compile,execute};
})();

const methods=new Set(["hold_range","focus","follow","protect","flank","stance","retreat_below","move_to","advance","withdraw","stop","patrol","rally","spread","tighten","kite","orbit","zigzag","seek_health","seek_ammo","seek_shield","seek_boost","reload","cooldown","reserve_fire","anti_air","avoid_danger","guard_point","brace","ram","hull_down","armor_piercing","smoke","sprint","ambush","suppress","grenade","strafe","hover","flare","rocket_pod","lock_on","backblast","bunker_buster","barrage","siege","displace","steady","headshot","camouflage","broadside","depth_charge","triage","field_hospital","repair","supply","scan","mark","focus_air","focus_ground","focus_armor","focus_support","focus_farthest","focus_low_shield","focus_high_damage","focus_unmarked","hold_fire","fire_at_will","seek_cover","leave_cover","retreat_to_spawn","scan_fast","repair_self","boost","vent_heat","shield_pulse","take_knee","breakaway","counter_battery","shore_bombard","recon_route","save_rockets","follow_patient","follow_vehicle","relocate","cover_infantry"]),sensors=new Set(["unit.hp_ratio","unit.ammo_ratio","unit.energy_ratio","unit.heat_ratio","unit.kind","unit.tier","unit.callsign","unit.x","unit.y","unit.shield","unit.reserve_ammo","unit.reloading","unit.enemy_distance","unit.enemy_kind","unit.has_enemy","unit.in_cover","unit.moving","unit.cooldown","squad.ally_count","squad.enemy_count","squad.leader_alive","squad.lowest_ally_hp","squad.elapsed","squad.map"]),queries=new Set(["unit.distance_to","unit.ally_health","unit.ally_alive","unit.enemies_within","unit.allies_within","unit.air_enemies_within","unit.armored_enemies_within","unit.foot_enemies_within","unit.health_drop_distance","unit.ammo_drop_distance","unit.shield_drop_distance","unit.boost_drop_distance","unit.nearest_cover_distance","unit.enemy_shield","unit.enemy_health","unit.incoming_shots","unit.has_ammo","unit.can_fire","unit.can_afford","unit.ability_ready","unit.map_is","unit.is_type","squad.has_type","squad.count_type","squad.injured_allies"]);
export function validatePython(text){const result=PythonUnit.compile(text,methods,sensors,queries);if(result.errors.length)throw Error(result.errors.join(" · "));return text}
