import {createEngine} from './engine.mjs';
import {validatePython} from '../../cloud/python-policy.mjs';
const types=['tank','infantry','rocket','scout','sniper','medic','artillery','engineer','boat','helicopter'];
const unlock={tank:1,infantry:1,rocket:1,scout:2,sniper:3,medic:3,artillery:4,engineer:4,boat:5,helicopter:6};
const ranges={tank:255,infantry:215,rocket:320,scout:245,sniper:390,medic:180,artillery:420,engineer:195,boat:340,helicopter:290};
const names={tank:'Tank',infantry:'Infantry',rocket:'Rocket soldier',scout:'Scout car',sniper:'Sniper',medic:'Medic',artillery:'Artillery',engineer:'Engineer',boat:'Boat',helicopter:'Helicopter'};
const token=n=>[...crypto.getRandomValues(new Uint8Array(n))].map(v=>v.toString(16).padStart(2,'0')).join('');
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const baseScript=type=>'def tick(unit, squad):\n    unit.focus("nearest")\n    unit.hold_range('+ranges[type]+')';
function newUnit(type,id){return{id,type,tier:1,name:names[type],unitScript:baseScript(type),instruction:baseScript(type),equipment:{},upgrades:{},skin:'olive',deployed:true,commands:['radar','gun','drive']}}
function strength(units){return Math.round(units.reduce((n,u)=>n+100*(1+.8*(u.tier-1))+Object.keys(u.equipment).length*12,0))}
async function account(env,input){if(['units','credits','resources','slots','tier','upgrades','inventory','winner','reward'].some(k=>Object.hasOwn(input,k)))throw Error('Online units and resources are server-owned. Submit scripts or a store action only.');let row=null,id=input.profile?.id,key=input.profile?.token;if(id){row=await env.DB.prepare('SELECT * FROM arena_profiles WHERE id=?').bind(id).first();if(!row||!key||row.token!==key)throw Error('Invalid player profile')}else{id=token(12);key=token(24)}const owned=row?.owned?JSON.parse(row.owned):{roster:[newUnit('tank','online-1')],credits:0,slots:1,gear:[],serial:1};return{id,key,row,original:row?.owned||'',owned}}
function catalog(a,level){const list=[{id:'slot',name:'Online team slot',price:100+(a.owned.slots-1)*50}];for(const type of types)if(level>=unlock[type])list.push({id:'recruit:'+type,name:'Recruit '+names[type],price:110+types.indexOf(type)*15});for(const slot of ['weapon','armor','utility'])for(let i=0;i<10;i++){const id=slot+'-'+i;if(!a.owned.gear.includes(id))list.push({id:'gear:'+id,name:slot+' '+(i+1),price:(slot==='weapon'?60:slot==='armor'?55:50)+i*(slot==='weapon'?18:slot==='armor'?15:14)})}return list}
async function saveAccount(env,input,item=null){const a=await account(env,input),owned=a.owned,name=String(input.name||a.row?.name||'Commander').trim().slice(0,28)||'Commander',map=['urban','canyon','volcanic','coast'].includes(input.map)?input.map:a.row?.map||'urban';const score=await env.DB.prepare('SELECT COUNT(*) AS wins FROM arena_results WHERE winner=?').bind(a.id).first(),level=1+Math.floor((score?.wins||0)/2);
 if(input.scripts!==undefined){if(!Array.isArray(input.scripts)||input.scripts.length>owned.roster.length)throw Error('Only owned units can receive scripts');const seen=new Set();for(const edit of input.scripts){if(!edit||Object.keys(edit).some(k=>!['id','unitScript','name','deployed'].includes(k)))throw Error('Only scripts, names and deployment can be edited');const unit=owned.roster.find(u=>u.id===edit.id);if(!unit||seen.has(edit.id))throw Error('Unit not owned');seen.add(edit.id);unit.unitScript=validatePython(edit.unitScript);unit.instruction=unit.unitScript;if(typeof edit.name==='string')unit.name=edit.name.slice(0,28);if(typeof edit.deployed==='boolean')unit.deployed=edit.deployed}}
 if(input.squadScript!==undefined){if(typeof input.squadScript!=='string')throw Error('Invalid squad script');owned.squadScript=input.squadScript?validatePython(input.squadScript):''}
 if(item){if(typeof item!=='string')throw Error('Invalid store item');if(item.startsWith('equip:')){const [,id,gear]=item.split(':'),unit=owned.roster.find(u=>u.id===id);if(!unit||!owned.gear.includes(gear))throw Error('Unit or equipment not owned');unit.equipment[gear.split('-')[0]]=gear}else if(item.startsWith('combine:')){const [,type,star]=item.split(':'),tier=Number(star),matches=owned.roster.filter(u=>u.type===type&&u.tier===tier);if(matches.length<3||tier>=3||tier<1)throw Error('Need three owned matching units');const keep=matches[0];keep.tier++;keep.commands=['radar','gun','drive','cover','duck',...(keep.tier===3?['perch','retreat']:[])];owned.roster=owned.roster.filter(u=>!matches.slice(1,3).includes(u))}else{const offer=catalog(a,level).find(o=>o.id===item);if(!offer)throw Error('Item locked or already owned');if(owned.credits<offer.price)throw Error('Not enough server credits');if(item==='slot'&&owned.slots>=15)throw Error('Maximum slots reached');if(item.startsWith('recruit:')&&owned.roster.length>=owned.slots)throw Error('Buy an online team slot first');owned.credits-=offer.price;if(item==='slot')owned.slots++;else if(item.startsWith('recruit:'))owned.roster.push(newUnit(item.slice(8),'online-'+(++owned.serial)));else owned.gear.push(item.slice(5))}}
 const units=owned.roster.filter(u=>u.deployed!==false&&(u.type!=='boat'||map==='coast')).map(u=>({...u,squadScript:u.unitScript,squadPython:owned.squadScript||''}));if(!units.length)throw Error('Deploy at least one compatible owned unit');const power=strength(units),serialized=JSON.stringify(owned),now=Date.now();if(a.row){const saved=await env.DB.prepare("UPDATE arena_profiles SET name=?,units=?,map=?,power=?,updated=?,owned=? WHERE id=? AND COALESCE(owned,'')=?").bind(name,JSON.stringify(units),map,power,now,serialized,a.id,a.original).run();if(!saved.meta.changes)throw Error('Account changed during request; reload and retry')}else await env.DB.prepare('INSERT INTO arena_profiles (id,token,name,units,map,power,updated,owned) VALUES (?,?,?,?,?,?,?,?)').bind(a.id,a.key,name,JSON.stringify(units),map,power,now,serialized).run();return{profile:{id:a.id,token:a.key},account:owned,catalog:catalog(a,level),level,power,units,map}}
async function activeMatch(env,id){return env.DB.prepare("SELECT code FROM arena_matches WHERE (attacker=? OR defender=?) AND expires>? AND (state IS NULL OR json_extract(state,'$.mode')='running') LIMIT 1").bind(id,id,Date.now()).first()}
async function award(env,row,state){if(!row.attacker||!row.defender)return;const winner=state.mode==='won'?row.attacker:row.defender,loser=state.mode==='won'?row.defender:row.attacker;await env.DB.prepare('INSERT OR IGNORE INTO arena_results (code,winner,loser,completed,paid) VALUES (?,?,?,?,0)').bind(row.code,winner,loser,Date.now()).run();await env.DB.batch([env.DB.prepare("UPDATE arena_profiles SET owned=json_set(owned,'$.credits',json_extract(owned,'$.credits')+60) WHERE id=? AND owned IS NOT NULL AND EXISTS(SELECT 1 FROM arena_results WHERE code=? AND paid=0)").bind(winner,row.code),env.DB.prepare("UPDATE arena_profiles SET owned=json_set(owned,'$.credits',json_extract(owned,'$.credits')+15) WHERE id=? AND owned IS NOT NULL AND EXISTS(SELECT 1 FROM arena_results WHERE code=? AND paid=0)").bind(loser,row.code),env.DB.prepare('UPDATE arena_results SET paid=1 WHERE code=? AND paid=0').bind(row.code)])}
export default {async fetch(request,env){const url=new URL(request.url);try{
 if(url.pathname==='/api/status')return json({available:false,model:'External Python script authoring',location:'No in-game model'});
 if(url.pathname==='/api/plan'||url.pathname==='/api/squad-chat')return json({error:'Paste Python scripts generated by your own LLM.'},410);
 if(!url.pathname.startsWith('/api/matches'))return env.ASSETS.fetch(request);if(!env.DB)return json({error:'Match database unavailable'},503);
 if(request.method==='GET'&&url.pathname==='/api/matches/leaderboard'){const result=await env.DB.prepare('SELECT p.name,p.power,(SELECT COUNT(*) FROM arena_results WHERE winner=p.id) AS wins,(SELECT COUNT(*) FROM arena_results WHERE loser=p.id) AS losses FROM arena_profiles p WHERE p.owned IS NOT NULL ORDER BY wins DESC,losses ASC,p.updated DESC LIMIT 30').all();return json({players:result.results})}
 if(request.method==='POST'){const raw=await request.text();if(raw.length>65000)return json({error:'Request too large'},413);const input=JSON.parse(raw);
 if(url.pathname==='/api/matches/cancel'){const a=await account(env,input);await env.DB.prepare('UPDATE arena_matches SET expires=? WHERE code=? AND attacker=? AND token_b IS NULL').bind(Date.now(),input.code,a.id).run();return json({status:'cancelled'})}
 if(url.pathname==='/api/matches/profile'||url.pathname==='/api/matches/shop'){const data=await saveAccount(env,input,url.pathname.endsWith('/shop')?input.item:null);return json(data)}
 if(url.pathname==='/api/matches/random'||url.pathname==='/api/matches/create'){const defense=await saveAccount(env,input);if(await activeMatch(env,defense.profile.id))throw Error('An online match is already active. Reconnect or cancel the waiting invite.');const code=token(3).toUpperCase(),session=token(24),seed=crypto.getRandomValues(new Uint32Array(1))[0],now=Date.now();if(url.pathname.endsWith('/create')){await env.DB.prepare('INSERT INTO arena_matches (code,token_a,units_a,map,seed,updated,expires,revision,attacker) VALUES (?,?,?,?,?,?,?,0,?)').bind(code,session,JSON.stringify(defense.units),defense.map,seed,now,now+900000,defense.profile.id).run();return json({...defense,code,token:session,status:'waiting',seat:0})}const candidates=await env.DB.prepare('SELECT id,units,map,power FROM arena_profiles WHERE id<>? AND owned IS NOT NULL AND map=? AND power BETWEEN ? AND ? ORDER BY ABS(power-?) LIMIT 20').bind(defense.profile.id,defense.map,defense.power*.65,defense.power*1.35,defense.power).all();if(!candidates.results.length)return json({...defense,status:'empty'});const opponent=candidates.results[crypto.getRandomValues(new Uint32Array(1))[0]%candidates.results.length],b=JSON.parse(opponent.units).map((u,i)=>({...u,id:'defender-'+i})),engine=createEngine(defense.units,b,defense.map,seed);await env.DB.prepare('INSERT INTO arena_matches (code,token_a,token_b,units_a,units_b,map,seed,state,updated,expires,revision,attacker,defender) VALUES (?,?,?,?,?,?,?,?,?,?,0,?,?)').bind(code,session,token(24),JSON.stringify(defense.units),JSON.stringify(b),defense.map,seed,JSON.stringify(engine.state()),now,now+900000,defense.profile.id,opponent.id).run();return json({...defense,code,token:session,status:'running',seat:0})}
 if(url.pathname==='/api/matches/join'){const code=String(input.code||'').toUpperCase(),row=await env.DB.prepare('SELECT * FROM arena_matches WHERE code=? AND expires>?').bind(code,Date.now()).first();if(!row)throw Error('Match not found or expired');if(row.token_b)throw Error('Match already has two players');const defense=await saveAccount(env,{...input,map:row.map});if(row.attacker===defense.profile.id)throw Error('Cannot fight your own profile');if(await activeMatch(env,defense.profile.id))throw Error('An online match is already active');const session=token(24),b=defense.units.map((u,i)=>({...u,id:'defender-'+i})),engine=createEngine(JSON.parse(row.units_a),b,row.map,row.seed),result=await env.DB.prepare('UPDATE arena_matches SET token_b=?,units_b=?,state=?,updated=?,revision=revision+1,defender=? WHERE code=? AND token_b IS NULL').bind(session,JSON.stringify(b),JSON.stringify(engine.state()),Date.now(),defense.profile.id,code).run();if(!result.meta.changes)throw Error('Match already joined');return json({...defense,code,token:session,status:'running',seat:1})}}
 if(request.method==='GET'){const code=url.searchParams.get('code'),key=request.headers.get('x-match-token');let row=await env.DB.prepare('SELECT * FROM arena_matches WHERE code=? AND expires>?').bind(code,Date.now()).first();if(!row)throw Error('Match not found or expired');const seat=key===row.token_a?0:key===row.token_b?1:-1;if(seat<0||!key)return json({error:'Invalid session token'},403);if(!row.token_b)return json({code,status:'waiting',seat});let state=JSON.parse(row.state);if(state.mode==='running'){const now=Date.now(),engine=createEngine(JSON.parse(row.units_a),JSON.parse(row.units_b),row.map,row.seed,state);engine.tick(Math.min(2,(now-row.updated)/1000));state=engine.state();const saved=await env.DB.prepare('UPDATE arena_matches SET state=?,updated=?,revision=revision+1 WHERE code=? AND revision=?').bind(JSON.stringify(state),now,code,row.revision).run();if(!saved.meta.changes){row=await env.DB.prepare('SELECT * FROM arena_matches WHERE code=?').bind(code).first();state=JSON.parse(row.state)}}if(state.mode!=='running')await award(env,row,state);return json({code,seat,seed:row.seed,map:row.map,status:state.mode==='running'?'running':'finished',winner:state.mode==='won'?0:1,...state})}
 return json({error:'Unknown match action'},400);
 }catch(e){console.error('Arena API:',e.message);return json({error:e.message},400)}}};
