import {createEngine} from './engine.mjs';
const types=['tank','infantry','helicopter','rocket','artillery','sniper','boat','medic','engineer','scout'],commands=['radar','gun','drive','cover','duck','perch','retreat'];
function randomToken(bytes){return [...crypto.getRandomValues(new Uint8Array(bytes))].map(v=>v.toString(16).padStart(2,'0')).join('')}
function squad(input,prefix){if(!Array.isArray(input)||!input.length||input.length>15)throw Error('Select 1–15 deployed units');return input.map((u,i)=>{if(!types.includes(u.type)||!Number.isInteger(u.tier)||u.tier<1||u.tier>3||typeof u.instruction!=='string'||u.instruction.length>2000)throw Error('Invalid unit data');const gear={};for(const slot of ['weapon','armor','utility'])if(new RegExp('^'+slot+'-[0-9]$').test(u.equipment?.[slot]||''))gear[slot]=u.equipment[slot];const allowed=commands.slice(0,u.tier===1?3:u.tier===2?5:7);let compiled=null;const p=u.compiled;if(p&&['rush','balanced','sniper'].includes(p.style)&&['always','inRange','stationary'].includes(p.firePolicy))compiled={style:p.style,preferred:Math.max(100,Math.min(500,Number(p.preferred)||255)),cover:allowed.includes('cover')&&!!p.cover,evade:allowed.includes('duck')&&!!p.evade,retreat:allowed.includes('retreat')&&!!p.retreat,coverBelow:Math.max(0,Math.min(.9,Number(p.coverBelow)||.5)),retreatBelow:Math.max(0,Math.min(.8,Number(p.retreatBelow)||.25)),firePolicy:p.firePolicy,explanation:''};return{id:prefix+i,type:u.type,tier:u.tier,instruction:u.instruction,squadScript:typeof u.squadScript==='string'&&u.squadScript.length<=3000?u.squadScript:'leader tank-1\nall focus nearest\nall follow leader',commands:Array.isArray(u.commands)?u.commands.filter(c=>allowed.includes(c)):allowed,equipment:gear,compiled,compiledText:u.instruction}})}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
export default {async fetch(request,env){const url=new URL(request.url);try{
 if(url.pathname==='/api/status')return json({available:false,model:'Use the Android phone model or local USB bridge',location:'No hosted model'});
 if(url.pathname==='/api/plan'||url.pathname==='/api/squad-chat')return json({error:'Models run on your phone or computer. Open the installed Android app to compile.'},503);
 if(!url.pathname.startsWith('/api/matches'))return env.ASSETS.fetch(request);
 if(!env.DB)return json({error:'Match database unavailable'},503);
 if(request.method==='POST'){
 if(Number(request.headers.get('content-length'))>120000)return json({error:'Squad too large'},413);const raw=await request.text();if(raw.length>120000)return json({error:'Squad too large'},413);const input=JSON.parse(raw);
 if(url.pathname==='/api/matches/create'){const code=randomToken(3).toUpperCase(),token=randomToken(24),seed=crypto.getRandomValues(new Uint32Array(1))[0],map=['urban','canyon','volcanic','coast'].includes(input.map)?input.map:'urban',units=squad(input.units,'a-'),now=Date.now();await env.DB.prepare('INSERT INTO arena_matches (code,token_a,units_a,map,seed,updated,expires,revision) VALUES (?,?,?,?,?,?,?,0)').bind(code,token,JSON.stringify(units),map,seed,now,now+900000).run();return json({code,token,status:'waiting',seat:0})}
 if(url.pathname==='/api/matches/join'){const code=String(input.code||'').toUpperCase(),row=await env.DB.prepare('SELECT * FROM arena_matches WHERE code=? AND expires>?').bind(code,Date.now()).first();if(!row)throw Error('Match not found or expired');if(row.token_b)throw Error('Match already has two players');const token=randomToken(24),b=squad(input.units,'b-'),a=JSON.parse(row.units_a),engine=createEngine(a,b,row.map,row.seed),state=JSON.stringify(engine.state());const updated=await env.DB.prepare('UPDATE arena_matches SET token_b=?,units_b=?,state=?,updated=?,revision=revision+1 WHERE code=? AND token_b IS NULL').bind(token,JSON.stringify(b),state,Date.now(),code).run();if(!updated.meta.changes)throw Error('Match already joined');return json({code,token,status:'running',seat:1})}
 }
 if(request.method==='GET'){const code=url.searchParams.get('code'),token=request.headers.get('x-match-token');let row=await env.DB.prepare('SELECT * FROM arena_matches WHERE code=? AND expires>?').bind(code,Date.now()).first();if(!row)throw Error('Match not found or expired');const seat=token===row.token_a?0:token===row.token_b?1:-1;if(seat<0||!token)return json({error:'Invalid session token'},403);if(!row.token_b)return json({code,status:'waiting',seat});let state=JSON.parse(row.state);if(state.mode==='running'){const now=Date.now(),elapsed=Math.min(2,(now-row.updated)/1000),engine=createEngine(JSON.parse(row.units_a),JSON.parse(row.units_b),row.map,row.seed,state);engine.tick(elapsed);state=engine.state();const next=await env.DB.prepare('UPDATE arena_matches SET state=?,updated=?,revision=revision+1 WHERE code=? AND revision=?').bind(JSON.stringify(state),now,code,row.revision).run();if(!next.meta.changes){row=await env.DB.prepare('SELECT * FROM arena_matches WHERE code=?').bind(code).first();state=JSON.parse(row.state)}}return json({code,seat,seed:row.seed,map:row.map,status:state.mode==='running'?'running':'finished',winner:state.mode==='won'?0:1,...state})}
 return json({error:'Unknown match action'},400);
 }catch(e){console.error('Arena API:',e.message);return json({error:e.message},400)}}};
